var util = require('util');
var escodegen = require('escodegen');

var meta = require('./package.json');
var parser = require('./lib/parser');
var helpers = require('./lib/helpers');
var Program = require('./lib/syntax/Program');
  
var header = '/* Generated by Continuation.js v' + meta.version + ' */\n';

exports.compile = function (code, options) {
  if (!options) {
    options = {};
  }
  
  var indent = '  ';
  if (options.tabIndent) {
    indent = '\t';
  } else if (options.indentSpaces) {
    indent = Array(options.indentSpaces + 1).join(c);
  }
  
  //Wrap whole file into a function
  code = '(function () {\n' + code + '\n}).call(this);\n';
  
  helpers.reset();
  var ast = parser.parse(code);
  ast.normalize();
  //console.error(util.inspect(ast, false, null, true));
  ast.transform();
  //console.error(util.inspect(ast, false, null, true));
  
  ast = new Program(ast.body[0].expression.callee.object.body.body);

  //ast = escodegen.attachComments(ast, ast.comments, ast.tokens);
  var code = escodegen.generate(ast, {
    format: {
      indent: {
        style: indent,
        base: 0
      },
    },
    comment: true,
  });
  
  return header + code;
};

//Alias
exports.transform = exports.compile;
